definitions:
  form.LoginForm:
    properties:
      name:
        type: string
      password:
        description: 这里有做简单验证，表示参数是必须的
        type: string
    required:
    - name
    - password
    type: object
  gin.H:
    additionalProperties: true
    type: object
info:
  contact: {}
  description: Gin swagger 示例项目 首页展示
  license: {}
  title: Gin swagger  展示在web端的title上
  version: 1.0 定义接口的版本
paths:
  /index/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - ApiKeyAuth: []
      summary: 主页接口
  /login/:
    post:
      description: 登录接口
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/form.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: 登录接口
securityDefinitions:
  ApiKeyAuth  API的认证方式:
    in: cookie 发送认证的方式
    name: token  后端获取认证值得方式
    type: apiKey
swagger: "2.0"
